# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: MavenBuildandPublishArtifacts
        displayName: Maven Build and Publish Artifacts
        steps:
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: 'Pay-As-You-Go (a355c32e-4a22-4b05-aab4-be236850fa6e)'
            KeyVaultName: 'nextopsakv01'
            SecretsFilter: '*'
            RunAsPreJob: true
        - task: TerraformTaskV2@2
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env'
            backendServiceArm: 'Pay-As-You-Go (a355c32e-4a22-4b05-aab4-be236850fa6e)'
            backendAzureRmResourceGroupName: 'NextOps'
            backendAzureRmStorageAccountName: 'nextopssat19'
            backendAzureRmContainerName: 'terraform'
            backendAzureRmKey: 'DEV/dev.tfstate'
        - task: TerraformTaskV2@2
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env'
            commandOptions: '--auto-approve'
            environmentServiceNameAzureRM: 'Pay-As-You-Go (a355c32e-4a22-4b05-aab4-be236850fa6e)'       
        - task: CmdLine@2
          inputs:
            script: 'mysql -h nextopsmysql-dev01.mysql.database.azure.com -u petclinic@nextopsmysql-dev01 -pP2ssw0rd@123 -p petclinic < "$(build.sourcesdirectory)/src/main/resources/db/mysql/data.sql"'
           