# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: MavenBuildandPublishArtifacts
        displayName: Maven Build and Publish Artifacts
        steps:
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: 'Pay-As-You-Go (a355c32e-4a22-4b05-aab4-be236850fa6e)'
            KeyVaultName: 'nextopsakv01'
            SecretsFilter: '*'
            RunAsPreJob: true
         