# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  vmImage: ubuntu-latest

variables: 
  vmImageName: 'ubuntu-latest'
  environmentName: 'webapp-env'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: BuildandPublishArtifacts
      displayName: BuildwithMaven and PublishBuild Artifacts
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'YAML_ProjectSC'
          KeyVaultName: 'nextopsakv01'
          SecretsFilter: '*'
          RunAsPreJob: true
      
      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(build.sourcesdirectory)/env'
          backendServiceArm: 'YAML_ProjectSC'
          backendAzureRmResourceGroupName: 'NextOps'
          backendAzureRmStorageAccountName: 'nextopstfsa01'
          backendAzureRmContainerName: 'terraform'
          backendAzureRmKey: 'DEV/dev.tfstate'
      
      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(build.sourcesdirectory)/env'
          commandOptions: '--auto-approve'
          environmentServiceNameAzureRM: 'YAML_ProjectSC'
        
      - task: MysqlDeploymentOnMachineGroup@1
        inputs:
          TaskNameSelector: 'SqlTaskFile'
          SqlFile: '$(build.sourcesdirectory)/src/main/resources/db/mysql/schema.sql'
          ServerName: 'nextopsmysql-dev01.mysql.database.azure.com'
          DatabaseName: 'petclinic'
          SqlUsername: 'petclinic@nextopsmysql-dev01'
          SqlPassword: '$(DBDevPass)'
      
      - task: MysqlDeploymentOnMachineGroup@1
        inputs:
          TaskNameSelector: 'SqlTaskFile'
          SqlFile: '$(build.sourcesdirectory)/src/main/resources/db/mysql/data.sql'
          ServerName: 'nextopsmysql-dev01.mysql.database.azure.com'
          DatabaseName: 'petclinic'
          SqlUsername: 'petclinic@nextopsmysql-dev01'
          SqlPassword: '$(DBDevPass)'
      
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          options: '-Ddb.script=mysql -Djpa.database=MYSQL -Djdbc.driverClassName=com.mysql.cj.jdbc.Driver -Djdbc.url=jdbc:mysql://nextopsmysql-dev01.mysql.database.azure.com:3306/petclinic?useUnicode=true -Djdbc.username=petclinic@nextopsmysql-dev01 -Djdbc.password=$(DBDevPass)'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/target/*.?(war|jar)'
          TargetFolder: '$(build.artifactstagingdirectory)/dev'
      
      - task: MysqlDeploymentOnMachineGroup@1
        inputs:
          TaskNameSelector: 'SqlTaskFile'
          SqlFile: '$(build.sourcesdirectory)/src/main/resources/db/mysql/schema.sql'
          ServerName: 'nextopsmysql-staging01.mysql.database.azure.com'
          DatabaseName: 'petclinic'
          SqlUsername: 'petclinic@nextopsmysql-staging01'
          SqlPassword: '$(DBStagePass)'
      
      - task: MysqlDeploymentOnMachineGroup@1
        inputs:
          TaskNameSelector: 'SqlTaskFile'
          SqlFile: '$(build.sourcesdirectory)/src/main/resources/db/mysql/data.sql'
          ServerName: 'nextopsmysql-staging01.mysql.database.azure.com'
          DatabaseName: 'petclinic'
          SqlUsername: 'petclinic@nextopsmysql-staging01'
          SqlPassword: '$(DBStagePass)'
      
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          options: '-Ddb.script=mysql -Djpa.database=MYSQL -Djdbc.driverClassName=com.mysql.cj.jdbc.Driver -Djdbc.url=jdbc:mysql://nextopsmysql-staging01.mysql.database.azure.com:3306/petclinic?useUnicode=true -Djdbc.username=petclinic@nextopsmysql-staging01 -Djdbc.password=$(DBStagePass)'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/target/*.?(war|jar)'
          TargetFolder: '$(build.artifactstagingdirectory)/stage'
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  condition: succeeded()
  jobs:
    - deployment: DeploytoLinuxDevWebApp
      displayName: 'DevDeploymentStage'
      environment: DevWebAppEnv
      pool:
        vmImage: $(vmImageName)
      strategy:
       runOnce:
         deploy:
          steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'YAML_ProjectSC'
              KeyVaultName: 'nextopsakv01'
              SecretsFilter: '*'
              RunAsPreJob: true
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'YAML_ProjectSC'
              appType: 'webAppLinux'
              appName: 'nextopsapp-dev-01'
              package: '$(Pipeline.Workspace)/drop/dev/target/*.?(war|jar)'
              runtimeStack: 'TOMCAT|8.5-jre8'

- stage: Deploy1
  displayName: Deploy to Staging
  dependsOn: Deploy
  condition: succeeded()
  jobs:
    - deployment: DeploytoLinuxStagingWebApp
      displayName: 'StagingDeploymentStage'
      environment: StaingWebAppEnv
      pool:
        vmImage: $(vmImageName)
      strategy:
       runOnce:
         deploy:
          steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'YAML_ProjectSC'
              KeyVaultName: 'nextopsakv01'
              SecretsFilter: '*'
              RunAsPreJob: true
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'YAML_ProjectSC'
              appType: 'webAppLinux'
              appName: 'nextopsapp-staging-01'
              package: '$(Pipeline.Workspace)/drop/stage/target/*.?(war|jar)'
              runtimeStack: 'TOMCAT|8.5-jre8'